server:
  port: 8123
  servlet:
    context-path: /jay
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: kong-picture-backend
  # session 配置
  session:
    store-type: redis
      # session 30 天过期
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kong_picture
    username: root
    password: kong0305
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: local
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    #password: 123456
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false  #驼峰
    #日志 仅在开发环境
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jaychou.kongpicturebackend.controller


